name: bc-week08-ej02

services:
  mongo:
    image: mongo:7
    container_name: bc-week08-ej02-mongo
    restart: unless-stopped
    ports:
      - "27023:27017"
    volumes:
      - ej02-mongo-data:/data/db

volumes:
  ej02-mongo-data:
