name: bc-week08-ej01

services:
  mongo:
    image: mongo:7
    container_name: bc-week08-ej01-mongo
    restart: unless-stopped
    ports:
      - "27022:27017"
    volumes:
      - ej01-mongo-data:/data/db

volumes:
  ej01-mongo-data:
