name: bc-week07-ej02-mongo
services:
  mongo:
    image: mongo:7
    container_name: bootcamp_auth_mongo_ej02
    restart: unless-stopped
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bootcamp
      MONGO_INITDB_ROOT_PASSWORD: bootcamp123
      MONGO_INITDB_DATABASE: bootcamp_auth_dev
    volumes:
      - mongo_auth_data:/data/db
volumes:
  mongo_auth_data:
